# Generated by Django 5.0.4 on 2024-05-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotemodule', '0002_remove_quote_title_quote_created_at_quote_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='Tilte',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
